### ISSUE TITLE
Add PUSH0 opcode

### ISSUE THREAD

**Issue by kadenzipfel** [smlxlio/evm.codes#240]
As of the Shanghai upgrade, the [PUSH0](https://eips.ethereum.org/EIPS/eip-3855) opcode was added, but it's not yet listed on evm.codes

**Comment by dorlevi** [comment]
<img width="1166" alt="Screenshot 2023-05-15 at 5 42 19 PM" src="https://github.com/smlxlio/evm.codes/assets/1457950/fc02c6eb-73d7-4536-bc70-7a364289e6db">
are you sure you had the right fork selected?

**Comment by kadenzipfel** [comment]
> <img alt="Screenshot 2023-05-15 at 5 42 19 PM" width="1166" src="https://user-images.githubusercontent.com/1457950/238479380-fc02c6eb-73d7-4536-bc70-7a364289e6db.png"> are you sure you had the right fork selected?

ahhh yes this was the problem, thanks!

**Comment by dorlevi** [comment]
no problem!
